import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import dp from '../../public/images/profile/developer-pic-1.png'
// const inter = Inter({ subsets: ['latin'] })
import Layout from '../Components/Layout';
import AnimateText from '@/Components/AnimateText';
import Link from 'next/link';
import {LinkArrow} from '../Components/Icons'
import HireMe from '@/Components/HireMe';
import TransitionEffect from '@/Components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Shubham Ghodkhande | Home</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect/>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={dp} alt='Shubham' className='w-full h-auto lg:hidden md:inline-block md:w-full' priority sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50px, 50vw'></Image>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimateText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="https://drive.google.com/file/d/1wOF-LXxF9HO-fGagZyKb-zfMa3Z4IYhE/view?usp=sharing" target={"_blank"} className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base' >Resume <LinkArrow className={'w-6 ml-1'}/> </Link>
                <Link href="mailto:shubhamg0615@gmail.com" target={"_blank"} className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'>Contact</Link>
              </div>  
            </div>
          </div>
        </Layout>
        {
        <HireMe/>
        }
      </main>
    </>
  )
}
